### ISSUE TITLE
Error when trying to two-finger scroll

### ISSUE THREAD

**Issue by mikethebro** [mikethebro/Honors-Capstone#18]
Clicking on the scroll bar works fine to scroll, but using the trackpad to try a two-finger scroll produces this error:

Traceback (most recent call last):
  File "main.py", line 174, in <module>
    main()
  File "main.py", line 170, in main
    root.mainloop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1277, in mainloop
    self.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by mikethebro** [comment]
Tkinter GUI was abandoned.
